### ISSUE TITLE
no such option in group AGENT: root_helper

### ISSUE THREAD

**Issue by irathore** [noironetworks/python-opflex-agent#21]
I ran into issue with distributed metadata and had to fix the cfg.CONFIG.AGENT.root_helper. This prevents from system to put the services file. Getting rid of this error fixed that issue and now I see files in the services directory. Here is the patch and the log, just a quick fix, now moving to more testing. This is yesterday’s kilo release on top of RDO kilo.
--- as_metadata_manager.py.orig
2015-12-11 15:16:04.664000000 -0500
+++ as_metadata_manager.py
2015-12-11 15:53:37.785000000 -0500
@@ -25,6 +25,7 @@
 
 from neutron.common import config as common_config
 from neutron.common import utils
+from neutron.agent.common import config
 from neutron.plugins.openvswitch.common import config as ovs_config  # noqa
 from oslo.config import cfg
 from oslo_log import log as logging
@@ -729,6 +730,7 @@
 def init_env():
     # importing ovs_config got OVS registered
     cfg.CONF.register_opts(gbp_opts, "OPFLEX")
+    config.register_root_helper(cfg.CONF)
     common_config.init(sys.argv[1:])
     common_config.setup_logging()
     utils.log_opt_values(LOG)

2015-12-10 23:57:31.877 6426 INFO neutron.common.config [-] /usr/bin/opflex-state-watcher version 2015.1.1
2015-12-10 23:57:31.882 6426 CRITICAL neutron [-] NoSuchOptError: no such option in group AGENT: root_helper
2015-12-10 23:57:31.882 6426 TRACE neutron Traceback (most recent call last):
2015-12-10 23:57:31.882 6426 TRACE neutron   File "/usr/bin/opflex-state-watcher", line 9, in <module>
2015-12-10 23:57:31.882 6426 TRACE neutron     load_entry_point('neutron-opflex-agent==2015.1.0', 'console_scripts', 'opflex-state-watcher')()
2015-12-10 23:57:31.882 6426 TRACE neutron   File "/usr/lib/python2.7/site-packages/opflexagent/as_metadata_manager.py", line 749, in state_watcher_main
2015-12-10 23:57:31.882 6426 TRACE neutron     StateWatcher().run()
2015-12-10 23:57:31.882 6426 TRACE neutron   File "/usr/lib/python2.7/site-packages/opflexagent/as_metadata_manager.py", line 373, in __init__
2015-12-10 23:57:31.882 6426 TRACE neutron     root_helper = cfg.CONF.AGENT.root_helper
2015-12-10 23:57:31.882 6426 TRACE neutron   File "/usr/lib/python2.7/site-packages/oslo_config/cfg.py", line 2520, in __getattr__
2015-12-10 23:57:31.882 6426 TRACE neutron     return self._conf._get(name, self._group)
2015-12-10 23:57:31.882 6426 TRACE neutron   File "/usr/lib/python2.7/site-packages/oslo_config/cfg.py", line 2242, in _get
2015-12-10 23:57:31.882 6426 TRACE neutron     value = self._do_get(name, group, namespace)
2015-12-10 23:57:31.882 6426 TRACE neutron   File "/usr/lib/python2.7/site-packages/oslo_config/cfg.py", line 2260, in _do_get
2015-12-10 23:57:31.882 6426 TRACE neutron     info = self._get_opt_info(name, group)
2015-12-10 23:57:31.882 6426 TRACE neutron   File "/usr/lib/python2.7/site-packages/oslo_config/cfg.py", line 2388, in _get_opt_info
2015-12-10 23:57:31.882 6426 TRACE neutron     raise NoSuchOptError(opt_name, group)
2015-12-10 23:57:31.882 6426 TRACE neutron NoSuchOptError: no such option in group AGENT: root_helper

**Comment by irathore** [comment]
Pasting again hoping format will be intact. Otherwise I will find a way
--- as_metadata_manager.py.orig
2015-12-11 15:16:04.664000000 -0500
+++ as_metadata_manager.py
2015-12-11 15:53:37.785000000 -0500
@@ -25,6 +25,7 @@
 
 from neutron.common import config as common_config
 from neutron.common import utils
+from neutron.agent.common import config
 from neutron.plugins.openvswitch.common import config as ovs_config  # noqa
 from oslo.config import cfg
 from oslo_log import log as logging
@@ -729,6 +730,7 @@
 def init_env():
     # importing ovs_config got OVS registered
     cfg.CONF.register_opts(gbp_opts, "OPFLEX")
+    config.register_root_helper(cfg.CONF)
     common_config.init(sys.argv[1:])
     common_config.setup_logging()
     utils.log_opt_values(LOG)

**Comment by amittbose** [comment]
Was fixed with https://github.com/noironetworks/python-opflex-agent/commit/0c63b691cb74fa71eb10a65ffc185570f2401194
